var countryList = [
		{"name" : "India", "value" : "IND"},
		{"name" : "America", "value" : "USA"},
		{"name" : "Australia", "value" : "AUS"},
		{"name" : "England", "value" : "ENG"},
		{"name" : "Canada", "value" : "CAN"},
		{"name" : "Europe", "value" : "EUR"},
]
var stateList = [
		{"name" : "karnataka", "value" : "kar"},
		{"name" : "kerela", "value" : "ker"},
		{"name" : "Andra", "value" : "AND"},
		{"name" : "uttar pradesh " ,"value" : "UP"},
		{"name" : "delhi", "value" : "DEL"},
		{"name" : "surat", "value" : "SUR"},
]
var bloodList = [
		{"name" : "A+", "value" : "Apos"},
		{"name" : "B+", "value" : "Bpos"},
		{"name" : "AB+", "value" : "ABpos"},
		{"name" : "A-" ,"value" : "Aneg"},
		{"name" : "B-", "value" : "Bneg"},
		{"name" : "AB-", "value" : "ABneg"},
		{"name" : "O+", "value" : "Opos"},
		{"name" : "O-", "value" : "Oneg"},
		{"name" : "OB+", "value" : "OBpos"},
        {"name" : "OB-", "value" : "OBneg"},
        {"name" : "Not sure", "value" : "NS"},

]
var minimumList = [
		
		{"name" : "0", "value" : "0"},
		{"name" : "1", "value" : "1"},
		{"name" : "2", "value" : "2"},
		{"name" : "3", "value" : "3"},
		{"name" : "4", "value" : "4"},
		{"name" : "5", "value" : "5"},
		{"name" : "6", "value" : "6"},
		{"name" : "7", "value" : "7"},
		{"name" : "8", "value" : "8"},
		{"name" : "9", "value" : "9"},
		{"name" : "10", "value" : "10"},
		{"name" : "11", "value" : "11"},
		{"name" : "12", "value" : "12"},
		{"name" : "13", "value" : "13"},
		{"name" : "14", "value" : "14"},
		{"name" : "15", "value" : "15"},
		{"name" : "16", "value" : "16"},
		{"name" : "17", "value" : "17"},
		{"name" : "18", "value" : "18"},
		{"name" : "19", "value" : "19"},
		{"name" : "20", "value" : "20"},
]
var maximumList = [
		
		{"name" : "0", "value" : "0"},
		{"name" : "1", "value" : "1"},
		{"name" : "2", "value" : "2"},
		{"name" : "3", "value" : "3"},
		{"name" : "4", "value" : "4"},
		{"name" : "5", "value" : "5"},
		{"name" : "6", "value" : "6"},
		{"name" : "7", "value" : "7"},
		{"name" : "8", "value" : "8"},
		{"name" : "9", "value" : "9"},
		{"name" : "10", "value" : "10"},
		{"name" : "11", "value" : "11"},
		{"name" : "12", "value" : "12"},
		{"name" : "13", "value" : "13"},
		{"name" : "14", "value" : "14"},
		{"name" : "15", "value" : "15"},
		{"name" : "16", "value" : "16"},
		{"name" : "17", "value" : "17"},
		{"name" : "18", "value" : "18"},
		{"name" : "19", "value" : "19"},
		{"name" : "20", "value" : "20"},
]

var districtList = [
		
		{"name" : "Bagalkote", "value" : "Bagalkote"},
		{"name" : "Bangalore Rural", "value" : "Bangalore Rural"},
		{"name" : "Bangalore Urban", "value" : "Bangalore Urban"},
		{"name" : "Belagavi", "value" : "Belagavi"},
		{"name" : "Bellary", "value" : "Bellary"},
		{"name" : "Bidar", "value" : "Bidar"},
		{"name" : "Bijapur", "value" : "Bijapur"},
		{"name" : "Chamrajanagara", "value" : "Chamrajanagara"},
		{"name" : "Chikkamagalur", "value" : "Chikkamagalur"},
		{"name" : "Chitradurga", "value" : "Chitradurga"},
		{"name" : "Dakshina Kannada", "value" : "Dakshina Kannada"},
		{"name" : "Davanagere", "value" : "Davanagere"},
		{"name" : "Dharwad", "value" : "Dharwad"},
		{"name" : "Gadag", "value" : "Gadag"},
		{"name" : "Gulbarga", "value" : "Gulbarga"},
		{"name" : "Hassan", "value" : "Hassan"},
		{"name" : "Haveri", "value" : "Haveri"},
		{"name" : "Kodagu", "value" : "Kodagu"},
		{"name" : "Kolar", "value" : "Kolar"},
		{"name" : "Koppal", "value" : "Koppal"},
		{"name" : "Mandya", "value" : "Mandya"},
		{"name" : "Mysore", "value" : "Mysore"},
		{"name" : "Raichur", "value" : "Raichur"},
		{"name" : "Shimoga", "value" : "Shimoga"},
		{"name" : "Tumkur", "value" : "Tumkur"},
		{"name" : "Udupi", "value" : "Udupi"},
		{"name" : "Uttara Kannada", "value" : "Uttara Kannada"},
		
]

var cityList = [
		
		{"name" : "Bagalkote", "value" : "Bagalkote"},
		{"name" : "Bangalore Rural", "value" : "Bangalore Rural"},
		{"name" : "Bangalore Urban", "value" : "Bangalore Urban"},
		{"name" : "Belagavi", "value" : "Belagavi"},
		{"name" : "Bellary", "value" : "Bellary"},
		{"name" : "Bidar", "value" : "Bidar"},
		{"name" : "Bijapur", "value" : "Bijapur"},
		{"name" : "Chamrajanagara", "value" : "Chamrajanagara"},
		{"name" : "Chikkamagalur", "value" : "Chikkamagalur"},
		{"name" : "Chitradurga", "value" : "Chitradurga"},
		{"name" : "Dakshina Kannada", "value" : "Dakshina Kannada"},
		{"name" : "Davanagere", "value" : "Davanagere"},
		{"name" : "Dharwad", "value" : "Dharwad"},
		{"name" : "Gadag", "value" : "Gadag"},
		{"name" : "Gulbarga", "value" : "Gulbarga"},
		{"name" : "Hassan", "value" : "Hassan"},
		{"name" : "Haveri", "value" : "Haveri"},
		{"name" : "Kodagu", "value" : "Kodagu"},
		{"name" : "Kolar", "value" : "Kolar"},
		{"name" : "Koppal", "value" : "Koppal"},
		{"name" : "Mandya", "value" : "Mandya"},
		{"name" : "Mysore", "value" : "Mysore"},
		{"name" : "Raichur", "value" : "Raichur"},
		{"name" : "Shimoga", "value" : "Shimoga"},
		{"name" : "Tumkur", "value" : "Tumkur"},
		{"name" : "Udupi", "value" : "Udupi"},
		{"name" : "Uttara Kannada", "value" : "Uttara Kannada"},
		
]

var ugList = [
             
			  {"name" : "BCOM", "value" : "BCOM"},
			  {"name" : "BBA", "value" : "BBA"},
			  {"name" : "BSC", "value" : "BSC"},
			  {"name" : "BCA", "value" : "BCA"},
			  {"name" : "BA", "value" : "BA"},
			  {"name" : "BE", "value" : "BE"},
			  
]

var brList = [
                 {"name" : "CIVIL BOARD", "value" : "CIVIL BOARD"},
				 {"name" : "ME BOARD", "value" : "ME BOARD"},
				 {"name" : "EC BOARD", "value" : "EC BOARD"},
				 {"name" : "E&E BOARD", "value" : "E&E BOARD"},
				 {"name" : "CSE BOARD", "value" : "CSE BOARD"},
				 {"name" : "IP BOARD", "value" : "IP BOARD"},
				 {"name" : "IT BOARD", "value" : "IT BOARD"},
				 {"name" : "BT BOARD", "value" : "BT BOARD"},
				 {"name" : "CHE BOARD", "value" : "CHE BOARD"},
				 {"name" : "AU BOARD", "value" : "AU BOARD"},
]

var pgList = [
              
			  {"name" : "MCOM", "value" : "MCOM"},
			  {"name" : "MBA", "value" : "MBA"},
			  {"name" : "MSC", "value" : "MSC"},
			  {"name" : "MCA", "value" : "MCA"},
			  {"name" : "MA", "value" : "MA"},
			  {"name" : "M.Tech", "value" : "M.Tech"},
]

var fromList = [
      
	           {"name" : "1990", "value" : "1990"},
			   {"name" : "1991", "value" : "1991"},
			   {"name" : "1992", "value" : "1992"},
			   {"name" : "1993", "value" : "1993"},
			   {"name" : "1994", "value" : "1994"},
			   {"name" : "1995", "value" : "1995"},
			   {"name" : "1996", "value" : "1996"},
			   {"name" : "1997", "value" : "1997"},
			   {"name" : "1998", "value" : "1998"},
			   {"name" : "1999", "value" : "1999"},
			   {"name" : "2000", "value" : "2000"},
			   {"name" : "2001", "value" : "2001"},
			   {"name" : "2002", "value" : "2002"},
			   {"name" : "2003", "value" : "2003"},
			   {"name" : "2004", "value" : "2004"},
			   {"name" : "2005", "value" : "2005"},
			   {"name" : "2006", "value" : "2006"},
			   {"name" : "2007", "value" : "2007"},
			   {"name" : "2008", "value" : "2008"},
			   {"name" : "2009", "value" : "2009"},
			   {"name" : "2010", "value" : "2010"},
			   {"name" : "2011", "value" : "2011"},
			   {"name" : "2012", "value" : "2012"},
			   {"name" : "2013", "value" : "2013"},
			   {"name" : "2014", "value" : "2014"},
			   {"name" : "2015", "value" : "2015"},
			   {"name" : "2016", "value" : "2016"},
			   {"name" : "2017", "value" : "2017"},
			   {"name" : "2018", "value" : "2018"},
			   {"name" : "2019", "value" : "2019"},
			   {"name" : "2020", "value" : "2020"},
			   
]

var fromList1 = [
      
	           {"name" : "1990", "value" : "1990"},
			   {"name" : "1991", "value" : "1991"},
			   {"name" : "1992", "value" : "1992"},
			   {"name" : "1993", "value" : "1993"},
			   {"name" : "1994", "value" : "1994"},
			   {"name" : "1995", "value" : "1995"},
			   {"name" : "1996", "value" : "1996"},
			   {"name" : "1997", "value" : "1997"},
			   {"name" : "1998", "value" : "1998"},
			   {"name" : "1999", "value" : "1999"},
			   {"name" : "2000", "value" : "2000"},
			   {"name" : "2001", "value" : "2001"},
			   {"name" : "2002", "value" : "2002"},
			   {"name" : "2003", "value" : "2003"},
			   {"name" : "2004", "value" : "2004"},
			   {"name" : "2005", "value" : "2005"},
			   {"name" : "2006", "value" : "2006"},
			   {"name" : "2007", "value" : "2007"},
			   {"name" : "2008", "value" : "2008"},
			   {"name" : "2009", "value" : "2009"},
			   {"name" : "2010", "value" : "2010"},
			   {"name" : "2011", "value" : "2011"},
			   {"name" : "2012", "value" : "2012"},
			   {"name" : "2013", "value" : "2013"},
			   {"name" : "2014", "value" : "2014"},
			   {"name" : "2015", "value" : "2015"},
			   {"name" : "2016", "value" : "2016"},
			   {"name" : "2017", "value" : "2017"},
			   {"name" : "2018", "value" : "2018"},
			   {"name" : "2019", "value" : "2019"},
			   {"name" : "2020", "value" : "2020"},
			   
]


