var countryList = [
		{"name" : "India", "value" : "IND"},
		{"name" : "America", "value" : "USA"},
		{"name" : "Australia", "value" : "AUS"},
		{"name" : "England", "value" : "ENG"},
		{"name" : "Canada", "value" : "CAN"},
		{"name" : "Europe", "value" : "EUR"},
]
var stateList = [
		{"name" : "karnataka", "value" : "kar"},
		{"name" : "kerela", "value" : "ker"},
		{"name" : "Andra", "value" : "AND"},
		{"name" : "uttar pradesh " ,"value" : "UP"},
		{"name" : "delhi", "value" : "DEL"},
		{"name" : "surat", "value" : "SUR"},
]
var bloodList = [
		{"name" : "A+", "value" : "Apos"},
		{"name" : "B+", "value" : "Bpos"},
		{"name" : "AB+", "value" : "ABpos"},
		{"name" : "A-" ,"value" : "Aneg"},
		{"name" : "B-", "value" : "Bneg"},
		{"name" : "AB-", "value" : "ABneg"},
		{"name" : "O+", "value" : "Opos"},
		{"name" : "O-", "value" : "Oneg"},
		{"name" : "OB+", "value" : "OBpos"},
        {"name" : "OB-", "value" : "OBneg"},
        {"name" : "Not sure", "value" : "NS"},

]

var minimumList = [
		
		{"name" : "0", "value" : "0"},
		{"name" : "1", "value" : "1"},
		{"name" : "2", "value" : "2"},
		{"name" : "3", "value" : "3"},
		{"name" : "4", "value" : "4"},
		{"name" : "5", "value" : "5"},
		{"name" : "6", "value" : "6"},
		{"name" : "7", "value" : "7"},
		{"name" : "8", "value" : "8"},
		{"name" : "9", "value" : "9"},
		{"name" : "10", "value" : "10"},
		{"name" : "11", "value" : "11"},
		{"name" : "12", "value" : "12"},
		{"name" : "13", "value" : "13"},
		{"name" : "14", "value" : "14"},
		{"name" : "15", "value" : "15"},
		{"name" : "16", "value" : "16"},
		{"name" : "17", "value" : "17"},
		{"name" : "18", "value" : "18"},
		{"name" : "19", "value" : "19"},
		{"name" : "20", "value" : "20"},
]
var maximumList = [
		
		{"name" : "0", "value" : "0"},
		{"name" : "1", "value" : "1"},
		{"name" : "2", "value" : "2"},
		{"name" : "3", "value" : "3"},
		{"name" : "4", "value" : "4"},
		{"name" : "5", "value" : "5"},
		{"name" : "6", "value" : "6"},
		{"name" : "7", "value" : "7"},
		{"name" : "8", "value" : "8"},
		{"name" : "9", "value" : "9"},
		{"name" : "10", "value" : "10"},
		{"name" : "11", "value" : "11"},
		{"name" : "12", "value" : "12"},
		{"name" : "13", "value" : "13"},
		{"name" : "14", "value" : "14"},
		{"name" : "15", "value" : "15"},
		{"name" : "16", "value" : "16"},
		{"name" : "17", "value" : "17"},
		{"name" : "18", "value" : "18"},
		{"name" : "19", "value" : "19"},
		{"name" : "20", "value" : "20"},
]